import {useMemo} from 'react';
const path=(points:number[][])=>points.map(([x,y],i)=>`${i?'L':'M'}${x.toFixed(2)},${y.toFixed(2)}`).join(' ');
function project(x:number,y:number,z:number){const a=.65,b=.45;const xx=x*Math.cos(a)-y*Math.sin(a),yy=x*Math.sin(a)+y*Math.cos(a);return[200+xx*67,120+(yy*Math.sin(b)+z*Math.cos(b))*67]}
export function Geometry({kind}:{kind:number}){
 const shapes=useMemo(()=>{
 if(kind===0){const rings=[];for(let i=0;i<30;i++){const u=i*2*Math.PI/30;const points=[];for(let j=0;j<=100;j++){const v=j*2*Math.PI/100;points.push(project((1.2+.48*Math.cos(v))*Math.cos(u),(1.2+.48*Math.cos(v))*Math.sin(u),.48*Math.sin(v)))}rings.push(path(points))}for(let i=0;i<14;i++){const v=i*2*Math.PI/14;const points=[];for(let j=0;j<=140;j++){const u=j*2*Math.PI/140;points.push(project((1.2+.48*Math.cos(v))*Math.cos(u),(1.2+.48*Math.cos(v))*Math.sin(u),.48*Math.sin(v)))}rings.push(path(points))}return rings}
 if(kind===2){const curves=[];for(let k=0;k<6;k++){const points=[];for(let j=0;j<=1200;j++){const t=j*6*Math.PI/1200,d=2.7+k*.18;points.push([200+23*(2*Math.cos(t)+d*Math.cos(2*t/3)),120+23*(2*Math.sin(t)-d*Math.sin(2*t/3))])}curves.push(path(points))}return curves}return[];
 },[kind]);
 return <svg className={'math-art math-'+kind} viewBox="0 0 400 240" role="img" aria-label={['Wireframe torus: circular symmetry in three dimensions','Golden-angle phyllotaxis: a spiral pattern at 137.508 degrees','Hypotrochoid curves: a five-fold symmetric geometric pattern'][kind]}><defs><radialGradient id={'math-glow-'+kind}><stop stopColor="currentColor" stopOpacity=".12"/><stop offset="1" stopColor="currentColor" stopOpacity="0"/></radialGradient></defs><rect width="400" height="240" fill={'url(#math-glow-'+kind+')'}/><g stroke="currentColor" fill="none" strokeWidth=".7" opacity=".18"><path d="M200 16V224M35 120H365"/><circle cx="200" cy="120" r="100" strokeDasharray="2 7"/></g>{kind===1?<g fill="currentColor">{Array.from({length:340},(_,i)=>{const angle=i*Math.PI*(3-Math.sqrt(5)),r=5.4*Math.sqrt(i);return <circle key={i} cx={(200+Math.cos(angle)*r).toFixed(3)} cy={(120+Math.sin(angle)*r).toFixed(3)} r={(1.1+1.1*i/340).toFixed(3)} opacity={(.45+.55*i/340).toFixed(3)}/>})}</g>:<g fill="none" stroke="currentColor" strokeWidth={kind===0?.65:.6} opacity=".8">{shapes.map((d,i)=><path key={i} d={d}/>)}</g>}<g fill="currentColor" fontFamily="monospace" fontSize="10" opacity=".75"><text x="18" y="25">{['S¹ × S¹','φ = (1 + √5) / 2','R : r = 5 : 3'][kind]}</text><text x="18" y="223" letterSpacing="2">{['01 / TORUS','02 / PHYLLOTAXIS','03 / HYPOTROCHOID'][kind]}</text><text x="373" y="223">∞</text></g></svg>
}
