"use client";
import {useCallback,useEffect,useState} from 'react';
import {flushSync} from 'react-dom';
import {ArrowUpRight,Sparkles,FlaskConical,Plus,MessageCircle,Send,PenLine} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Music} from './music';
import {Prologue} from './prologue';
import {Geometry} from './geometry';
import {samples,type Post} from './samples';
import {sitesService,type LabService} from './lab-service';
import {Turnstile} from './turnstile';
type Comment={id:string;name:string;body:string;createdAt:number};
const categories=['all','thoughts','perspectives','finds'];
const blank={title:'',titleEn:'',body:'',bodyEn:'',category:'thoughts',id:''};
export default function Home({service=sitesService,onManage,onBlog,onRead,skipIntro=false}:{service?:LabService;onManage?:()=>void;onBlog?:()=>void;onRead?:(post:Post)=>void;skipIntro?:boolean}={}){
 const[intro,setIntro]=useState(!skipIntro);
 const enterLab=useCallback(()=>{setIntro(false);requestAnimationFrame(()=>document.getElementById('journal-title')?.focus())},[]);
 const[en,setEn]=useState(false),[filter,setFilter]=useState('all'),[posts,setPosts]=useState<Post[]>([]),[comments,setComments]=useState<Comment[]>([]),[signedIn,setSignedIn]=useState(false),[owner,setOwner]=useState(false),[canClaim,setCanClaim]=useState(false),[loadError,setLoadError]=useState(''),[loading,setLoading]=useState(true),[reader,setReader]=useState<Post|null>(null),[editor,setEditor]=useState(false),[draft,setDraft]=useState(blank),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[name,setName]=useState(''),[message,setMessage]=useState(''),[notice,setNotice]=useState('');
 const[guestPosting,setGuestPosting]=useState(false),[siteKey,setSiteKey]=useState(''),[challenge,setChallenge]=useState(''),[challengeReset,setChallengeReset]=useState(0),[trap,setTrap]=useState('');
 const t=(zh:string,eng:string)=>en?eng:zh;
 const refresh=useCallback(async()=>{try{const d=await service.load();setPosts(d.posts);setComments(d.comments);setSignedIn(d.signedIn);setOwner(d.isOwner);setCanClaim(d.canClaim);setGuestPosting(!!d.guestPosting);setSiteKey(d.turnstileSiteKey||'');setLoadError('');}catch(e){setLoadError((e as Error).message)}finally{setLoading(false)}},[service]);
 useEffect(()=>{void refresh();try{setEn(localStorage.getItem('wonder-language')==='en')}catch{}},[refresh]);
 useEffect(()=>{document.documentElement.lang=en?'en':'zh-CN';try{localStorage.setItem('wonder-language',en?'en':'zh')}catch{}},[en]);
 useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(mc.registerTool({name:'set_journal_category',description:'Filter the visible journal entries by category.',inputSchema:{type:'object',properties:{category:{type:'string',enum:categories}},required:['category'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!input||!categories.includes(input.category))throw Error('Invalid category');flushSync(()=>{setIntro(false);setFilter(input.category)});document.getElementById('journal')?.scrollIntoView({behavior:'smooth'});return{category:input.category}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 async function mutate(data:unknown){return service.mutate(data)}
 async function openEditor(){if(onManage){onManage();return}setFormError('');if(!signedIn){window.location.assign('/signin-with-chatgpt?return_to=/');return}setBusy(true);try{if(canClaim){await mutate({action:'claim'});await refresh()}setDraft(blank);setEditor(true)}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
 async function savePost(e:React.FormEvent){e.preventDefault();setBusy(true);setFormError('');try{await mutate({action:'post',...draft});await refresh();setEditor(false);setDraft(blank);setNotice(t('发布成功，新的脑洞已上线。','Published. A new thought is out in the wild.'));setFilter('all');}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
 async function leaveComment(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setNotice('');try{const result=await mutate({action:'comment',name,body:message,website:trap,turnstileToken:challenge});setMessage('');await refresh();setNotice(result.pending?t('脑电波已保存，主人审核后会公开显示。','Your message is saved and will appear after review.'):t('收到你的脑电波了！','Your signal has arrived!'));}catch(e){setNotice((e as Error).message)}finally{setBusy(false);setChallengeReset(n=>n+1)}}
 const entries=posts.length?posts:service.mode==='sites'||service.mode==='preview'||service.mode==='unconfigured'?samples:[];const visible=entries.filter(p=>filter==='all'||p.category===filter);
 const title=(p:Post)=>en?(p.titleEn||p.title):p.title;const body=(p:Post)=>en?(p.bodyEn||p.body):p.body;
 if(intro)return <main><Prologue en={en} onFinish={enterLab}/></main>;
 return <main><header className="header"><a href="#" className="brand"><FlaskConical/><span>Wonder <i>Lab</i></span></a><nav><Button variant="ghost" className="header-intro" onClick={()=>setIntro(true)}>{t('开场动画','Watch intro')}</Button>{onBlog?<button onClick={onBlog}>{t('灵感广场','Blog')}</button>:<a href="#journal">{t('思绪漫游','The journal')}</a>}<a href="#guestbook">{t('来留个言','Guestbook')}</a>{onManage&&<button className="home-write" onClick={onManage}>{t('登录 / 写文章','Sign in / Write')}</button>}</nav><Button variant="ghost" onClick={()=>setEn(!en)} aria-label={t('切换到英文','Switch to Chinese')}><span className={!en?'language-active':''}>中</span><span className="dim">/</span><span className={en?'language-active':''}>EN</span></Button></header>
 <section className="hero"><div className="hero-art"/><div className="hero-copy"><div className="eyebrow"><span/> A PERSONAL EXPERIMENT IN CURIOSITY</div><h1 id="journal-title" tabIndex={-1}>{en?<>A mind.<br/>A little <em>wild.</em></>:<>脑洞大开，<br/><em>不必合理。</em></>}</h1><p>{t('一些不着边际的思考，一点认真生活的偏爱。','Thoughts, happy accidents, and things worth getting lost in.')}<br/>{t('欢迎误入，我的奇思妙想实验室。','Welcome to my little corner of the strange.')}</p><a className="hero-link" href="#journal">{t('随便逛逛','Wander a little')}<ArrowUpRight size={20}/></a></div><span className="orbit-label">STAY CURIOUS<br/>STAY A LITTLE WEIRD ✳</span><div className="hero-footer"><span>FIELD NOTES FROM AN UNTIDY MIND</span><span>SCROLL TO EXPLORE ↓</span></div></section>
 <div className="ticker" aria-hidden="true">THINK OUTSIDE THE MUSHROOM <Sparkles/> 保持好奇，允许奇怪 <Sparkles/> IDEAS GROW WILD HERE <Sparkles/> THINK OUTSIDE THE MUSHROOM <Sparkles/></div>
 <section id="journal" className="journal"><div className="section-head"><div><span className="eyebrow">THE JOURNAL / 01</span><h2>{t('新鲜出炉的脑内活动','Fresh from my brain')}<span>↗</span></h2></div>{(owner||canClaim||onManage)?<Button variant="outline" onClick={openEditor} disabled={busy}><Plus size={16}/>{t('写点什么','Write something')}</Button>:<span className="side-note">{t('什么都聊一点。','A little bit of everything.')}</span>}</div>
 <div className="filters" aria-label={t('文章分类','Journal categories')}>{categories.map((c,i)=><Button key={c} variant={filter===c?'default':'ghost'} className={filter===c?'active':''} onClick={()=>setFilter(c)} aria-pressed={filter===c}>{t(['全部灵感','奇思','妙想','私藏推荐'][i],['Everything','Thoughts','Perspectives','Good finds'][i])}{c==='all'&&<span>{String(entries.length).padStart(2,'0')}</span>}</Button>)}</div>
 {loadError&&<div className="error-box" role="alert">{loadError}<Button variant="outline" onClick={refresh}>{t('重试','Retry')}</Button></div>}
 <div className="cards">{visible.map((p)=>{const i=Math.max(0,categories.indexOf(p.category)-1);return <button type="button" className={'card card-'+i} key={p.id} onClick={()=>onRead&&!p.sample?onRead(p):setReader(p)}><div className="card-visual"><Geometry kind={i}/></div><div className="card-body"><div className="card-meta"><span>{['奇思 / THOUGHTS','妙想 / PERSPECTIVES','私藏 / FINDS'][i]}</span><span>{p.sample?t('示例','SAMPLE'):new Date(p.createdAt).toLocaleDateString(en?'en-CA':'zh-CN')}</span></div><h3>{title(p)}</h3><p>{body(p).split('\n')[0]}</p><div className="card-bottom"><span>{Math.max(1,Math.ceil(body(p).length/(en?1000:400)))} MIN READ</span><ArrowUpRight size={20}/></div></div></button>})}</div>{!visible.length&&<p className="empty">{t('这个角落还在发芽。','This corner is still growing.')}</p>}
 </section>
 <section id="guestbook" className="guestbook"><span className="eyebrow">LEAVE A LITTLE TRACE / 02</span><h2>{t('来都来了，留点脑电波。','You were here.')}<MessageCircle/></h2><p>{t('一个突然的想法、一份私藏，或者只是一句嗨。','A thought, a recommendation, or just a hello.')}</p><p className="guest-policy">{guestPosting?t('留言经审核后公开。昵称和正文会展示在页面上，请不要填写私人信息。','Messages appear publicly after review. Please keep private details out of your name and message.'):service.mode!=='sites'?t('当前可浏览设计；留言连接完成后会在这里开放。','Explore the design for now. Messages will open here once the connection is ready.'):''}</p><div className="guest-grid"><form onSubmit={leaveComment} className="guest-form"><label htmlFor="name">{t('怎么称呼你','Your name')}</label><Input id="name" value={name} onChange={e=>setName(e.target.value)} maxLength={40} required placeholder={t('路过的地球人','A passing earthling')}/><label htmlFor="message">{t('此刻的脑电波','What’s on your mind?')}</label><Textarea id="message" value={message} onChange={e=>setMessage(e.target.value)} required maxLength={1000} placeholder={t('把你的奇思妙想留在这里…','Leave a little of your strange here…')}/><label className="guest-trap" aria-hidden="true">Website<Input value={trap} onChange={e=>setTrap(e.target.value)} tabIndex={-1} autoComplete="off"/></label>{siteKey&&<Turnstile siteKey={siteKey} onToken={setChallenge} reset={challengeReset} en={en}/>}<div className="form-bottom"><span>{message.length} / 1000</span>{(signedIn||guestPosting)?<Button type="submit" disabled={busy||!!siteKey&&!challenge}>{busy?t('发送中…','Sending…'):t('发射脑电波','Send a signal')}<Send size={16}/></Button>:service.mode!=='sites'?<span className="guest-unavailable">{t('留言暂未开放','Guestbook not connected yet')}</span>:<a className="sign-in" href="/signin-with-chatgpt?return_to=/%23guestbook" target="_top">{t('登录后留言','Sign in to leave a note')}<ArrowUpRight size={16}/></a>}</div></form><div className="comment-list" aria-live="polite">{loading?<p className="empty">{t('正在接收脑电波…','Tuning in…')}</p>:comments.length?comments.map(c=><article className="comment" key={c.id}><div className="comment-top"><span className="avatar">{c.name.slice(0,1)}</span><strong>{c.name}</strong><time>{new Date(c.createdAt).toLocaleDateString(en?'en-CA':'zh-CN')}</time></div><p>{c.body}</p></article>):<div className="empty-note"><Sparkles/><h3>{t('第一束脑电波，会是你的吗？','Will yours be the first signal?')}</h3><p>{t('这里还很安静，留一句话，让想法相遇。','It’s quiet here. Leave a note and let ideas meet.')}</p></div>}</div></div><p className="notice" role="status">{notice}</p></section>
 <footer><span>Wonder <i>Lab</i></span><span>A WORK IN PROGRESS. JUST LIKE ME.</span><Button variant="ghost" onClick={openEditor} disabled={busy||(!owner&&!canClaim&&signedIn)}><PenLine size={14}/>{onManage?t('我的写作台','My studio'):t('写作台','Writing desk')}</Button></footer><Music en={en}/>
 <Dialog open={!!reader} onOpenChange={o=>!o&&setReader(null)}><DialogContent className="reading-modal"><DialogTitle>{reader&&title(reader)}</DialogTitle><DialogDescription>{reader?.sample?t('示例文章 · 等待你的真实想法','Sample entry · Waiting for your thoughts'):t('Wonder Lab · 脑内记录','Wonder Lab · Field notes')}</DialogDescription>{reader&&<div className="article-text">{en&&!reader.bodyEn&&<p className="translation-note">This entry is available in Chinese.</p>}{body(reader).split('\n\n').map((text,i)=><p key={i}>{text}</p>)}</div>}{owner&&reader&&!reader.sample&&<Button variant="outline" onClick={()=>{setDraft({...reader,titleEn:reader.titleEn||'',bodyEn:reader.bodyEn||''});setReader(null);setFormError('');setEditor(true)}}><PenLine/>{t('编辑文章','Edit entry')}</Button>}</DialogContent></Dialog>
 <Dialog open={editor} onOpenChange={o=>!busy&&setEditor(o)}><DialogContent className="editor-modal"><DialogTitle>{t(draft.id?'让想法再长一会儿':'种下一颗新想法',draft.id?'Let it grow a little more':'Plant a new thought')}</DialogTitle><DialogDescription>{t('中文必填；英文可选。未提供译文时显示原文。','Chinese is required; English is optional. Entries fall back to the original.')}</DialogDescription><form onSubmit={savePost} className="editor-form"><label>{t('分类','Category')}<Select value={draft.category} onValueChange={category=>setDraft({...draft,category})}><SelectTrigger aria-label={t('分类','Category')}><SelectValue/></SelectTrigger><SelectContent>{categories.slice(1).map((c,i)=><SelectItem key={c} value={c}>{t(['奇思','妙想','私藏推荐'][i],['Thoughts','Perspectives','Good finds'][i])}</SelectItem>)}</SelectContent></Select></label><label>{t('中文标题','Chinese title')}<Input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} required maxLength={160}/></label><label>{t('中文正文','Chinese body')}<Textarea value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} required maxLength={20000}/></label><label>{t('英文标题（可选）','English title (optional)')}<Input value={draft.titleEn} onChange={e=>setDraft({...draft,titleEn:e.target.value})} maxLength={160}/></label><label>{t('英文正文（可选）','English body (optional)')}<Textarea value={draft.bodyEn} onChange={e=>setDraft({...draft,bodyEn:e.target.value})} maxLength={20000}/></label><p className="error-text" role="alert">{formError}</p><Button disabled={busy} type="submit">{busy?t('保存中…','Saving…'):t(draft.id?'保存修改':'发布文章',draft.id?'Save changes':'Publish entry')}<ArrowUpRight/></Button></form></DialogContent></Dialog>
 </main>
}
