import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const compiled=ts.transpileModule(fs.readFileSync('backend/worker.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const {default:worker,sha256,flushNotifications}=await import('data:text/javascript;base64,'+Buffer.from(compiled).toString('base64'));
function d1(){const sql=new DatabaseSync(':memory:');sql.exec(fs.readFileSync('backend/migrations/0001_init.sql','utf8'));const prepare=query=>{let values=[];return {bind(...args){values=args;return this},async first(){return sql.prepare(query).get(...values)||null},async all(){return{results:sql.prepare(query).all(...values),success:true}},async run(){const result=sql.prepare(query).run(...values);return{success:true,meta:{changes:Number(result.changes)}}}}};return{sql,prepare,async batch(statements){sql.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.all());sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}}}}
async function fixture(){const db=d1();const env={DB:db,SITE_URL:'https://mmm1122.github.io/wonderlab/',ADMIN_KEY_SHA256:await sha256('test-admin-secret'),IP_HASH_SECRET:'a'.repeat(64),NOTIFY_TO:'owner@example.com'};const work=[];const ctx={waitUntil(p){work.push(p)}};
 const call=async(path,body,token,origin='https://mmm1122.github.io',ip='192.0.2.1')=>{const headers={'CF-Connecting-IP':ip};if(origin)headers.Origin=origin;if(body!==undefined)headers['Content-Type']='application/json';if(token)headers.Authorization='Bearer '+token;const response=await worker.fetch(new Request('https://api.example.com'+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)}),env,ctx);return{response,status:response.status,data:await response.json()}};
 const login=async()=>{const r=await call('/api/login',{key:'test-admin-secret'});assert.equal(r.status,200);return r.data.token};return{db,env,work,ctx,call,login}}
const post={action:'post',title:'Hello',titleEn:'Hello',body:'中文正文',bodyEn:'English body',category:'thoughts',status:'draft'};
test('rejects foreign and missing origins for writes; preflights only the configured site',async()=>{const f=await fixture();assert.equal((await f.call('/api/lab',{action:'comment',name:'a',body:'b'},null,'https://evil.example')).status,403);assert.equal((await f.call('/api/lab',{},null,null)).status,403);const r=await worker.fetch(new Request('https://api.example.com/api/lab',{method:'OPTIONS',headers:{Origin:'https://mmm1122.github.io'}}),f.env,f.ctx);assert.equal(r.status,204);assert.equal(r.headers.get('Access-Control-Allow-Origin'),'https://mmm1122.github.io')});
test('admin routes reject anonymous users and incorrect keys',async()=>{const f=await fixture();assert.equal((await f.call('/api/admin')).status,401);assert.equal((await f.call('/api/admin',post)).status,401);assert.equal((await f.call('/api/login',{key:'wrong'})).status,401)});
test('drafts stay private; publishing, editing, unpublishing and deleting work',async()=>{const f=await fixture(),token=await f.login();assert.equal((await f.call('/api/admin',post,token)).status,200);assert.deepEqual((await f.call('/api/lab')).data.posts,[]);const saved=(await f.call('/api/admin',undefined,token)).data.posts[0];assert.equal(saved.status,'draft');await f.call('/api/admin',{...post,id:saved.id,status:'published'},token);assert.equal((await f.call('/api/lab')).data.posts.length,1);await f.call('/api/admin',{...post,id:saved.id,title:'Edited',status:'draft'},token);assert.equal((await f.call('/api/admin',undefined,token)).data.posts[0].title,'Edited');assert.equal((await f.call('/api/lab')).data.posts.length,0);await f.call('/api/admin',{action:'deletePost',id:saved.id},token);assert.equal((await f.call('/api/admin',undefined,token)).data.postCount,0)});
test('comments persist privately, can be approved or hidden, and do not expose notification data publicly',async()=>{const f=await fixture(),token=await f.login();const r=await f.call('/api/lab',{action:'comment',name:'Visitor',body:'A nice idea'});assert.equal(r.status,201);assert.equal(r.data.pending,true);assert.equal((await f.call('/api/lab')).data.comments.length,0);const admin=(await f.call('/api/admin',undefined,token)).data;assert.equal(admin.pendingCount,1);assert.equal(admin.notificationsConfigured,false);assert.equal(admin.comments[0].notificationStatus,'pending');await f.call('/api/admin',{action:'moderate',id:r.data.id,status:'approved'},token);const published=(await f.call('/api/lab')).data.comments;assert.equal(published.length,1);assert.equal(published[0].notificationStatus,undefined);await f.call('/api/admin',{action:'moderate',id:r.data.id,status:'hidden'},token);assert.equal((await f.call('/api/lab')).data.comments.length,0)});
test('validates fields and keeps SQL-looking text as literal content',async()=>{const f=await fixture(),token=await f.login();assert.equal((await f.call('/api/admin',{...post,title:'',status:'published'},token)).status,400);assert.equal((await f.call('/api/lab',{action:'comment',name:'n',body:'x'.repeat(1001)})).status,400);assert.equal((await f.call('/api/admin',{...post,body:"'); DROP TABLE posts; --"},token)).status,200);assert.equal((await f.call('/api/admin',undefined,token)).data.postCount,1)});
test('session expiry, logout and key rotation revoke access; only token hashes are stored',async()=>{const f=await fixture();let token=await f.login();assert.notEqual(f.db.sql.prepare('SELECT token_hash FROM sessions').get().token_hash,token);await f.call('/api/logout',{},token);assert.equal((await f.call('/api/admin',undefined,token)).status,401);token=await f.login();f.db.sql.exec('UPDATE sessions SET expires_at=0');assert.equal((await f.call('/api/admin',undefined,token)).status,401);token=await f.login();f.env.ADMIN_KEY_SHA256=await sha256('rotated');assert.equal((await f.call('/api/admin',undefined,token)).status,401)});
test('login and guestbook limits persist in D1; honeypot is rejected',async()=>{const f=await fixture();for(let i=0;i<5;i++)assert.equal((await f.call('/api/login',{key:'wrong'})).status,401);assert.equal((await f.call('/api/login',{key:'wrong'})).status,429);assert.equal((await f.call('/api/lab',{action:'comment',name:'n',body:'b',website:'spam'})).status,400);for(let i=0;i<2;i++)assert.equal((await f.call('/api/lab',{action:'comment',name:'n',body:'b'})).status,201);assert.equal((await f.call('/api/lab',{action:'comment',name:'n',body:'b'})).status,429);assert(!JSON.stringify(f.db.sql.prepare('SELECT * FROM rate_limits').all()).includes('192.0.2.1'))});
test('missing backend secrets fail closed',async()=>{const f=await fixture();f.env.ADMIN_KEY_SHA256='';assert.equal((await f.call('/api/login',{key:'test-admin-secret'})).status,503);assert.equal((await f.call('/api/lab')).status,503)});
test('notification failure never loses a comment and can be retried',async()=>{const f=await fixture();f.env.NOTIFY_FROM='site@example.com';f.env.EMAIL={send:async()=>{throw Error('mail down')}};const r=await f.call('/api/lab',{action:'comment',name:'Visitor',body:'Please keep this'});await Promise.all(f.work);assert.equal(r.status,201);assert.equal(f.db.sql.prepare('SELECT count(*) AS n FROM comments').get().n,1);assert.equal(f.db.sql.prepare('SELECT status FROM notifications').get().status,'pending');let sent;f.env.EMAIL={send:async message=>{sent=message;return{messageId:'test'}}};f.db.sql.exec('UPDATE notifications SET next_attempt=0');await flushNotifications(f.env);assert.equal(f.db.sql.prepare('SELECT status FROM notifications').get().status,'sent');assert.equal(sent.to,'owner@example.com');assert(sent.text.includes('Please keep this'))});
test('concurrent notification flushes lease a message only once',async()=>{const f=await fixture();await f.call('/api/lab',{action:'comment',name:'Visitor',body:'One notification'});let sends=0;f.env.NOTIFY_FROM='site@example.com';f.env.EMAIL={send:async()=>{sends++;await new Promise(r=>setTimeout(r,5))}};await Promise.all([flushNotifications(f.env),flushNotifications(f.env)]);assert.equal(sends,1)});
test('final exhausted notification lease becomes visibly failed; manual retry works',async()=>{const f=await fixture(),token=await f.login();const r=await f.call('/api/lab',{action:'comment',name:'Visitor',body:'Retry me'});f.env.NOTIFY_FROM='site@example.com';f.env.EMAIL={send:async()=>({messageId:'ok'})};f.db.sql.exec("UPDATE notifications SET status='sending',attempts=5,locked_until=0");await flushNotifications(f.env);assert.equal(f.db.sql.prepare('SELECT status FROM notifications').get().status,'failed');await f.call('/api/admin',{action:'retryNotification',id:r.data.id},token);await Promise.all(f.work);assert.equal(f.db.sql.prepare('SELECT status FROM notifications').get().status,'sent')});
test('deleting a message also removes its notification job',async()=>{const f=await fixture(),token=await f.login();const r=await f.call('/api/lab',{action:'comment',name:'Visitor',body:'Delete me'});await f.call('/api/admin',{action:'deleteComment',id:r.data.id},token);assert.equal(f.db.sql.prepare('SELECT count(*) AS n FROM notifications').get().n,0);assert.equal((await f.call('/api/admin',undefined,token)).data.commentCount,0)});
test('admin pagination exposes older records and keeps the private API authenticated',async()=>{const f=await fixture(),token=await f.login();for(let i=0;i<21;i++)await f.call('/api/admin',{...post,title:'Post '+i},token);assert.equal((await f.call('/api/admin',undefined,token)).data.posts.length,20);assert.equal((await f.call('/api/admin?postPage=1',undefined,token)).data.posts.length,1);assert.equal((await f.call('/api/admin?postPage=-1',undefined,token)).status,400)});
test('partially configured Turnstile fails closed',async()=>{const f=await fixture();f.env.TURNSTILE_SITE_KEY='public';assert.equal((await f.call('/api/lab',{action:'comment',name:'n',body:'b'})).status,503);assert.equal(f.db.sql.prepare('SELECT count(*) AS n FROM comments').get().n,0)});
