import {useEffect,useState} from 'react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {Textarea} from '../components/ui/textarea';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {api,hasSession,login,logout} from './api';
type Post={id:string;title:string;titleEn:string;body:string;bodyEn:string;category:string;status:string};
type Note={id:string;name:string;body:string;status:string;createdAt:number;notificationStatus:string;notificationError?:string};
type Overview={posts:Post[];comments:Note[];postCount:number;commentCount:number;pendingCount:number;notificationsConfigured:boolean;turnstileConfigured:boolean};
const blank:Post={id:'',title:'',titleEn:'',body:'',bodyEn:'',category:'thoughts',status:'draft'};
export function Admin({open,onClose,onChanged,connected,initialTab='posts'}:{open:boolean;onClose:()=>void;onChanged:()=>void;connected:boolean;initialTab?:'posts'|'comments'}){
 const[authed,setAuthed]=useState(hasSession),[key,setKey]=useState(''),[data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[draft,setDraft]=useState<Post|null>(null),[pp,setPP]=useState(0),[cp,setCP]=useState(0),[tab,setTab]=useState<'posts'|'comments'>(initialTab),[confirm,setConfirm]=useState<{action:string;id:string;title:string}|null>(null);
 async function refresh(){try{const result=await api<Overview>(`/api/admin?postPage=${pp}&commentPage=${cp}`,undefined,true);setData(result);setError('')}catch(e){setError((e as Error).message);if(!hasSession())setAuthed(false)}}
 useEffect(()=>{if(open&&authed)void refresh()},[open,authed,pp,cp]);
 async function signIn(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await login(key);setKey('');setAuthed(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function change(payload:unknown,success='已保存 / Saved'){setBusy(true);setError('');setNotice('');try{await api('/api/admin',payload,true);setNotice(success);await refresh();onChanged();return true}catch(e){setError((e as Error).message);if(!hasSession())setAuthed(false);return false}finally{setBusy(false)}}
 async function save(e:React.FormEvent){e.preventDefault();if(draft&&await change({action:'post',...draft},draft.status==='draft'?'草稿已保存，仅你可见 / Draft saved, visible only to you':'文章已发布 / Article published'))setDraft(null)}
 function close(){if(busy)return;if(draft){setConfirm({action:'discard',id:'',title:'放弃尚未保存的修改？ / Discard unsaved changes?'});return}onClose()}
 const status=(s:string)=>({draft:'草稿 / Draft',published:'已发布 / Published',pending:'待审核 / Pending',approved:'已公开 / Approved',hidden:'已隐藏 / Hidden'}[s]||s);
 return <Dialog open={open} onOpenChange={v=>!v&&close()}><DialogContent className="admin-modal"><DialogTitle>Wonder Lab · 管理后台 / Dashboard</DialogTitle><DialogDescription>写下想法，审核留言。 / Write, publish, and review messages.</DialogDescription>
 {!connected?<p className="admin-info">后台尚未连接。部署后端并填写站点配置后，即可在这里登录。 / Connect the backend in the site configuration to enable the dashboard.</p>:!authed?<form onSubmit={signIn} className="admin-login"><label>管理员密钥 / Administrator key<Input type="password" value={key} autoComplete="current-password" onChange={e=>setKey(e.target.value)} required/></label><p>密钥只用于本次登录，不会保存在网页文件里。 / Your key is used to sign in and is not stored in the page.</p><Button disabled={busy} type="submit">{busy?'登录中… / Signing in…':'登录 / Sign in'}</Button></form>:<>
 <div className="admin-toolbar"><Button variant={tab==='posts'?'default':'outline'} onClick={()=>setTab('posts')}>文章 / Posts {data?.postCount??''}</Button><Button variant={tab==='comments'?'default':'outline'} onClick={()=>setTab('comments')}>留言 / Messages {data?.pendingCount?`(${data.pendingCount} 待审核)` : ''}</Button><Button variant="ghost" disabled={busy} onClick={()=>void refresh()}>刷新 / Refresh</Button><Button variant="ghost" disabled={busy} onClick={async()=>{if(draft){setError('请先保存或取消编辑。 / Save or cancel editing first.');return}await logout().catch(()=>{});setAuthed(false);setData(null);onChanged()}}>退出 / Sign out</Button></div>
 {data&&!data.notificationsConfigured&&<p className="admin-info">留言会正常保存在这里。邮箱提醒尚未连接。 / Messages are saved here; email notifications are not configured yet.</p>}
 {tab==='posts'&&<><Button disabled={!!draft||busy} onClick={()=>setDraft({...blank})}>写新文章 / New article</Button>{draft&&<form className="admin-editor" onSubmit={save}><label>分类 / Category<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}><option value="thoughts">奇思 / Thoughts</option><option value="perspectives">妙想 / Perspectives</option><option value="finds">私藏 / Finds</option></select></label><label>状态 / Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option value="draft">草稿，仅自己可见 / Private draft</option><option value="published">公开发布 / Published</option></select></label><label>中文标题 / Chinese title<Input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} required maxLength={160}/></label><label>中文正文 / Chinese body<Textarea rows={8} value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} required maxLength={20000}/></label><label>英文标题，可选 / English title, optional<Input value={draft.titleEn} onChange={e=>setDraft({...draft,titleEn:e.target.value})} maxLength={160}/></label><label>英文正文，可选 / English body, optional<Textarea rows={8} value={draft.bodyEn} onChange={e=>setDraft({...draft,bodyEn:e.target.value})} maxLength={20000}/></label><div className="admin-actions"><Button type="submit" disabled={busy}>{busy?'保存中… / Saving…':draft.status==='draft'?'保存草稿 / Save draft':'发布 / Publish'}</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>setConfirm({action:'discard',id:'',title:'放弃尚未保存的修改？ / Discard unsaved changes?'})}>取消 / Cancel</Button></div></form>}
 <div className="admin-list">{data?.posts.map(p=><article key={p.id}><div><strong>{p.title}</strong><span className="admin-status">{status(p.status)}</span></div><div className="admin-actions"><Button variant="outline" disabled={busy||!!draft} onClick={()=>setDraft({...p})}>编辑 / Edit</Button><Button variant="ghost" disabled={busy||!!draft} onClick={()=>setConfirm({action:'deletePost',id:p.id,title:`永久删除「${p.title}」？ / Delete this article permanently?`})}>删除 / Delete</Button></div></article>)}{data&&!data.posts.length&&<p>这里还没有文章，先写一篇草稿吧。 / Start with your first draft.</p>}</div>
 <div className="admin-pages"><Button variant="outline" disabled={!pp||busy||!!draft} onClick={()=>setPP(n=>n-1)}>上一页 / Previous</Button><span>{pp+1}</span><Button variant="outline" disabled={!data||(pp+1)*20>=data.postCount||busy||!!draft} onClick={()=>setPP(n=>n+1)}>下一页 / Next</Button></div></>}
 {tab==='comments'&&<><div className="admin-list">{data?.comments.map(c=><article key={c.id}><div><strong>{c.name}</strong><span className="admin-status">{status(c.status)}</span><time>{new Date(c.createdAt).toLocaleString()}</time></div><p className="admin-note-body">{c.body}</p><p className="admin-delivery">邮件 / Email: {c.notificationStatus==='sent'?'已提交给邮件服务 / Submitted to email service':c.notificationStatus==='failed'?'发送失败 / Failed':data.notificationsConfigured?'等待发送 / Queued':'等待配置 / Awaiting setup'}</p><div className="admin-actions">{c.status!=='approved'&&<Button disabled={busy} onClick={()=>void change({action:'moderate',id:c.id,status:'approved'},'留言已公开 / Message approved')}>公开 / Approve</Button>}{c.status!=='hidden'&&<Button variant="outline" disabled={busy} onClick={()=>void change({action:'moderate',id:c.id,status:'hidden'},'留言已隐藏 / Message hidden')}>隐藏 / Hide</Button>}<Button variant="ghost" disabled={busy} onClick={()=>setConfirm({action:'deleteComment',id:c.id,title:`永久删除 ${c.name} 的留言？ / Delete this message permanently?`})}>删除 / Delete</Button>{c.notificationStatus==='failed'&&<Button variant="outline" disabled={busy||!data.notificationsConfigured} onClick={()=>void change({action:'retryNotification',id:c.id},'通知已重新排队 / Notification queued again')}>重试邮件 / Retry email</Button>}</div></article>)}{data&&!data.comments.length&&<p>尚未收到留言。 / No messages yet.</p>}</div><div className="admin-pages"><Button variant="outline" disabled={!cp||busy} onClick={()=>setCP(n=>n-1)}>上一页 / Previous</Button><span>{cp+1}</span><Button variant="outline" disabled={!data||(cp+1)*20>=data.commentCount||busy} onClick={()=>setCP(n=>n+1)}>下一页 / Next</Button></div></>}
 </>}
 {confirm&&<div className="admin-confirm" role="alert"><p>{confirm.title}</p><div className="admin-actions"><Button disabled={busy} onClick={async()=>{if(confirm.action==='discard'){setDraft(null);setConfirm(null);return}if(await change({action:confirm.action,id:confirm.id},'已删除 / Deleted'))setConfirm(null)}}>确认 / Confirm</Button><Button variant="outline" disabled={busy} onClick={()=>setConfirm(null)}>返回 / Back</Button></div></div>}
 {error&&<p className="error-text" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 </DialogContent></Dialog>;
}
