import {useEffect,useState} from 'react';
import {ArrowUpRight,FlaskConical,PenLine,ArrowLeft} from 'lucide-react';
import {Geometry} from '../app/geometry';
import {Button} from '../components/ui/button';
import {api} from './api';
import {navigate,routeHref} from './routes';
export type Article={id:string;slug:string;title:string;titleEn:string;body:string;bodyEn:string;category:string;status:'draft'|'published';createdAt:number;updatedAt:number;version:number;authorId:string;authorName:string};
export type Member={id:string;email:string|null;displayName:string;bio:string;role:'member'|'owner'};
export function RouteLink({to,children,className}:{to:string;children:React.ReactNode;className?:string}){return <a className={className} href={routeHref(to)} onClick={e=>{if(e.button===0&&!e.metaKey&&!e.ctrlKey&&!e.shiftKey&&!e.altKey){e.preventDefault();navigate(to)}}}>{children}</a>}
export function LabHeader(){return <header className="lab-header"><RouteLink to="/" className="brand"><FlaskConical/><span>Wonder <i>Lab</i></span></RouteLink><nav><RouteLink to="/">首页 / Home</RouteLink><RouteLink to="/blog">灵感广场 / Blog</RouteLink><RouteLink to="/admin" className="lab-write-link"><PenLine size={16}/> 写作台 / My studio</RouteLink></nav></header>}
export function Blog({slug}:{slug?:string}){
 const[posts,setPosts]=useState<Article[]>([]),[post,setPost]=useState<Article|null>(null),[page,setPage]=useState(0),[total,setTotal]=useState(0),[category,setCategory]=useState('all'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[en,setEn]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setError('');setPost(null);setPosts([]);(slug?api<{post:Article}>('/api/posts/'+encodeURIComponent(slug)).then(r=>{if(active)setPost(r.post)}):api<{posts:Article[];total:number}>(`/api/posts?page=${page}&category=${category}`).then(r=>{if(active){setPosts(r.posts);setTotal(r.total)}})).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[slug,page,category,retry]);
 const title=(p:Article)=>en?(p.titleEn||p.title):p.title,body=(p:Article)=>en?(p.bodyEn||p.body):p.body;
 return <div className="lab-shell"><LabHeader/><main className="lab-main"><div className="lab-page-top"><RouteLink to={slug?'/blog':'/'}><ArrowLeft size={16}/> {slug?'返回文章 / All posts':'首页 / Home'}</RouteLink><Button variant="outline" onClick={()=>setEn(!en)}>{en?'中文':'English'}</Button></div>{slug?<>{loading&&<p role="status">正在打开文章… / Loading article…</p>}{post&&<article className="lab-reading"><span className="eyebrow">{post.category.toUpperCase()} / FIELD NOTES</span><h1>{title(post)}</h1><div className="lab-byline">{post.authorName} · {new Date(post.createdAt).toLocaleDateString()}</div><div className="lab-reading-art"><Geometry kind={Math.max(0,['thoughts','perspectives','finds'].indexOf(post.category))}/></div><div className="lab-prose">{body(post).split('\n\n').map((p,i)=><p key={i}>{p}</p>)}</div></article>}</>:<><span className="eyebrow">MANY MINDS, ONE CURIOUS WORLD</span><h1 className="lab-display">让想法，<em>在这里相遇。</em><small>A place for curious minds.</small></h1><div className="lab-filters">{['all','thoughts','perspectives','finds'].map((c,i)=><Button key={c} variant={category===c?'default':'ghost'} aria-pressed={category===c} onClick={()=>{setCategory(c);setPage(0)}}>{['全部 / All','奇思 / Thoughts','妙想 / Perspectives','私藏 / Finds'][i]}</Button>)}</div>{loading?<p role="status">正在收集灵感… / Loading…</p>:<div className="lab-post-grid">{posts.map(p=><RouteLink to={'/blog/'+p.slug} key={p.id} className="lab-post-card"><div className="lab-card-art"><Geometry kind={Math.max(0,['thoughts','perspectives','finds'].indexOf(p.category))}/></div><div className="lab-card-content"><span className="lab-byline">{p.authorName} · {new Date(p.createdAt).toLocaleDateString()}</span><h2>{title(p)}</h2><p>{body(p).slice(0,150)}</p><span className="lab-read-more">走进这个想法 / Read story <ArrowUpRight size={18}/></span></div></RouteLink>)}</div>}{!loading&&!error&&!posts.length&&<div className="lab-empty"><Geometry kind={1}/><h2>第一个想法，等你种下。</h2><p>Write a little. Let it grow.</p><RouteLink to="/admin">写一篇文章 / Start writing →</RouteLink></div>}<div className="admin-pages"><Button variant="outline" disabled={!page||loading} onClick={()=>setPage(p=>p-1)}>上一页 / Previous</Button><span>{page+1} / {Math.max(1,Math.ceil(total/20))}</span><Button variant="outline" disabled={(page+1)*20>=total||loading} onClick={()=>setPage(p=>p+1)}>下一页 / Next</Button></div></>}{error&&<div className="lab-error" role="alert">{error}<Button variant="outline" onClick={()=>setRetry(n=>n+1)}>重试 / Retry</Button></div>}</main></div>;
}
