import {useEffect,useRef,useState} from 'react';
import {Plus,PenLine,Send,FileText,LogOut,ArrowUpRight} from 'lucide-react';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {Textarea} from '../components/ui/textarea';
import {Geometry} from '../app/geometry';
import {api,hasSession,login,logout,verifyCode} from './api';
import {LabHeader,RouteLink,type Member,type Article} from './blog';
import {Admin} from './admin';
import {setNavigationGuard} from './routes';
type Draft=Pick<Article,'id'|'title'|'titleEn'|'body'|'bodyEn'|'category'|'status'|'version'>;
const blank:Draft={id:'',title:'',titleEn:'',body:'',bodyEn:'',category:'thoughts',status:'draft',version:1};
export function Studio({connected}:{connected:boolean}){
 const[user,setUser]=useState<Member|null>(null),[checking,setChecking]=useState(true),[enabled,setEnabled]=useState(false),[email,setEmail]=useState(''),[challenge,setChallenge]=useState(''),[code,setCode]=useState(''),[key,setKey]=useState(''),[wait,setWait]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[posts,setPosts]=useState<Article[]>([]),[page,setPage]=useState(0),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[draft,setDraft]=useState<Draft|null>(null),[baseline,setBaseline]=useState(''),[preview,setPreview]=useState(false),[moderate,setModerate]=useState(false),[profile,setProfile]=useState(false),[name,setName]=useState(''),[bio,setBio]=useState('');
 const dirty=!!draft&&JSON.stringify(draft)!==baseline,form=useRef<HTMLFormElement>(null);
 useEffect(()=>{let active=true;if(!connected){setChecking(false);return}void api<{emailLoginEnabled:boolean}>('/api/auth/config').then(r=>{if(active)setEnabled(r.emailLoginEnabled)}).catch(()=>{});if(hasSession())void api<{user:Member}>('/api/auth/me',undefined,true).then(r=>{if(active){setUser(r.user);setName(r.user.displayName);setBio(r.user.bio)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setChecking(false)});else setChecking(false);return()=>{active=false}},[connected]);
 useEffect(()=>{if(wait<=0)return;const timer=setTimeout(()=>setWait(s=>s-1),1000);return()=>clearTimeout(timer)},[wait]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);setNavigationGuard(()=>!dirty||window.confirm('离开将放弃尚未保存的修改。 / Leave without saving?'));return()=>{window.removeEventListener('beforeunload',warn);setNavigationGuard(null)}},[dirty]);
 async function refresh(){setLoading(true);try{const r=await api<{posts:Article[];total:number}>(`/api/posts?mine=1&page=${page}`,undefined,true);setPosts(r.posts);setTotal(r.total);setError('')}catch(e){setError((e as Error).message);if(!hasSession())setUser(null)}finally{setLoading(false)}}
 useEffect(()=>{if(user)void refresh()},[user?.id,page]);
 async function signedIn(){const r=await api<{user:Member}>('/api/auth/me',undefined,true);setUser(r.user);setName(r.user.displayName);setBio(r.user.bio);setKey('');setCode('');setChallenge('');setPage(0);setPosts([]);setDraft(null);setNotice('欢迎回来。 / Welcome to your studio.');setError('')}
 async function requestCode(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await api<{challengeId:string}>('/api/auth/request-code',{email});setChallenge(r.challengeId);setCode('');setWait(60);setNotice('验证码已发送，请检查邮箱和垃圾邮件。 / Check your inbox for the code.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function emailSignIn(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await verifyCode(challenge,code);await signedIn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function ownerSignIn(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await login(key);await signedIn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function edit(post:Draft){if(dirty&&!window.confirm('放弃未保存的修改？ / Discard unsaved edits?'))return;const next={id:post.id,title:post.title,titleEn:post.titleEn,body:post.body,bodyEn:post.bodyEn,category:post.category,status:post.status,version:post.version};setDraft(next);setBaseline(JSON.stringify(next));setPreview(false);setError('');setNotice('')}
 async function save(status:'draft'|'published'){
  if(!draft||!form.current?.reportValidity())return;setBusy(true);setError('');setNotice('');try{
   const r=await api<{post:Article}>(draft.id?'/api/posts/'+draft.id:'/api/posts',{...draft,status},true,draft.id?'PUT':'POST');
   const next={...draft,id:r.post.id,status:r.post.status,version:r.post.version};setDraft(next);setBaseline(JSON.stringify(next));
   await refresh();setNotice(status==='published'?'文章已发布到灵感广场。 / Your article is now public.':'草稿已保存，仅自己可见。 / Private draft saved.');
  }catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 async function remove(post:Article){if(!window.confirm(`永久删除「${post.title}」？此操作无法撤销。 / Permanently delete this article?`))return;setBusy(true);setError('');try{await api('/api/posts/'+post.id,undefined,true,'DELETE');if(posts.length===1&&page>0)setPage(p=>p-1);else await refresh();setNotice('文章已删除。 / Article deleted.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function signOut(){if(dirty&&!window.confirm('退出会放弃未保存的修改。 / Sign out without saving?'))return;setBusy(true);try{await logout();setUser(null);setPosts([]);setDraft(null);setProfile(false);setNotice('已退出。 / Signed out.');setError('')}catch(e){setUser(null);setPosts([]);setDraft(null);setError((e as Error).message)}finally{setBusy(false)}}
 async function saveProfile(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await api<{user:Member}>('/api/profile',{displayName:name,bio},true,'PUT');setUser(r.user);setProfile(false);setNotice('个人资料已更新。 / Profile updated.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="lab-shell"><LabHeader/><main className="lab-main lab-studio">
 {checking?<p role="status">正在打开你的写作台… / Opening your studio…</p>:!user?<div className="lab-auth-layout"><section className="lab-auth-story"><span className="eyebrow">A LITTLE SPACE, ALL YOUR OWN</span><h1 className="lab-display">把脑洞，<br/><em>写成故事。</em></h1><p>一个账号，一方自己的小天地。<br/>Save a private draft. Share it when you’re ready.</p><Geometry kind={2}/></section><section className="lab-auth-card"><span className="eyebrow">WELCOME TO WONDER LAB</span><h2>登录 / Create your space</h2><p>首次验证邮箱会自动创建账号，无需设置密码。<br/>Your first email sign-in creates your account.</p>{!connected?<p className="admin-info">这是离线预览，请到在线网站登录。 / Sign in on the live website.</p>:<><form onSubmit={requestCode}><label>邮箱 / Email<Input type="email" autoComplete="email" value={email} maxLength={254} required disabled={busy} onChange={e=>{setEmail(e.target.value);setChallenge('');setCode('')}} placeholder="you@example.com"/></label><Button type="submit" disabled={busy||!enabled||wait>0}>{wait>0?`${wait}s 后可重发 / Resend`:'发送登录验证码 / Send code'}</Button></form>{!enabled&&<p className="admin-info">公众邮箱登录即将开放，发信服务正在配置。站主现在可以使用下方密钥入口写文章。 / Public email sign-in is being connected.</p>}{challenge&&<form onSubmit={emailSignIn}><label>8 位验证码 / 8-digit code<Input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{8}" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,8))} required maxLength={8}/></label><Button disabled={busy} type="submit">验证并登录 / Verify & sign in</Button><small>10 分钟内有效；验证码不会出现在网址里。 / Valid for 10 minutes.</small></form>}<details className="lab-owner-login"><summary>站主密钥入口 / Owner access</summary><form onSubmit={ownerSignIn}><label>管理员密钥 / Administrator key<Input type="password" autoComplete="current-password" value={key} onChange={e=>setKey(e.target.value)} required/></label><Button disabled={busy} type="submit">进入写作台 / Open studio</Button></form></details></>}</section></div>:<>
 <div className="lab-studio-heading"><div><span className="eyebrow">YOUR IDEAS LIVE HERE</span><h1>{user.displayName}<em> 的写作台</em></h1><p>{user.email||'Wonder Lab owner'} · 只有你能管理自己的文章。 / Your posts, your space.</p></div><div className="admin-actions"><Button variant="outline" disabled={busy||!!draft} onClick={()=>setProfile(!profile)}>个人资料 / Profile</Button>{user.role==='owner'&&<Button variant="outline" disabled={busy||!!draft} onClick={()=>setModerate(true)}>审核留言 / Messages</Button>}<Button variant="ghost" disabled={busy} onClick={()=>void signOut()}><LogOut size={15}/>退出 / Sign out</Button></div></div>
 {profile&&<form onSubmit={saveProfile} className="lab-profile"><label>公开昵称 / Public display name<Input value={name} onChange={e=>setName(e.target.value)} maxLength={60} required/></label><label>关于我 / About me<Textarea value={bio} onChange={e=>setBio(e.target.value)} maxLength={500}/></label><p>邮箱不会显示在公开文章中。 / Your email stays private.</p><Button disabled={busy} type="submit">保存资料 / Save profile</Button></form>}
 {draft?<section className="lab-editor"><div className="lab-editor-toolbar"><Button variant="ghost" disabled={busy} onClick={()=>{if(!dirty||window.confirm('放弃未保存的修改？ / Discard unsaved edits?')){setDraft(null);setPreview(false)}}}>← 我的文章 / My posts</Button><span>{dirty?'尚未保存 / Unsaved':draft.id?'已保存 / Saved':'新文章 / New post'} · {draft.status==='published'?'公开 / Public':'私密草稿 / Private'}</span><Button variant="outline" onClick={()=>setPreview(!preview)}>{preview?'继续编辑 / Edit':'预览 / Preview'}</Button></div><form ref={form} onSubmit={e=>{e.preventDefault();void save('draft')}}>{preview?<article className="lab-prose"><h1>{draft.title||'Untitled'}</h1>{draft.body.split('\n\n').map((p,i)=><p key={i}>{p}</p>)}</article>:<><label className="lab-title-label">标题 / Title<Input className="lab-title-input" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} required maxLength={160} placeholder="给这个想法起个名字…"/></label><label>正文 / Your story<Textarea className="lab-body-input" value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} required maxLength={20000} placeholder="不用完美，先写下来。 / Start anywhere."/></label><div className="lab-editor-meta"><label>分类 / Category<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}><option value="thoughts">奇思 / Thoughts</option><option value="perspectives">妙想 / Perspectives</option><option value="finds">私藏 / Finds</option></select></label><span>{draft.body.length.toLocaleString()} / 20,000</span></div><details><summary>添加英文版本 / Add an English version</summary><label>英文标题 / English title<Input value={draft.titleEn} onChange={e=>setDraft({...draft,titleEn:e.target.value})} maxLength={160}/></label><label>英文正文 / English body<Textarea rows={10} value={draft.bodyEn} onChange={e=>setDraft({...draft,bodyEn:e.target.value})} maxLength={20000}/></label></details></>}
 <div className="lab-save-bar"><p>{draft.status==='published'?'保存为草稿会撤下公开文章。 / Saving as draft unpublishes it.':'草稿仅你可见，发布后所有人可读。 / Drafts are private; published posts are public.'}</p><Button variant="outline" type="button" disabled={busy||preview} onClick={()=>void save('draft')}><FileText size={16}/>保存草稿 / Save draft</Button><Button type="button" disabled={busy||preview} onClick={()=>void save('published')}><Send size={16}/>{busy?'保存中…':'发布 / Publish'}</Button></div></form></section>:<><div className="lab-list-heading"><h2>我的文章 / My posts <span>{total}</span></h2><Button onClick={()=>edit({...blank})}><Plus size={18}/>写新文章 / New post</Button></div>{loading?<p role="status">正在加载文章… / Loading…</p>:<div className="lab-draft-list">{posts.map(post=><article key={post.id}><div className={'lab-post-status '+post.status}>{post.status==='draft'?'草稿 / Draft':'已发布 / Published'}</div><h3>{post.title}</h3><p>{post.body.slice(0,110)}</p><div className="lab-draft-bottom"><time>{new Date(post.updatedAt).toLocaleString()}</time><div className="admin-actions">{post.status==='published'&&<RouteLink to={'/blog/'+post.slug}>查看 / Read <ArrowUpRight size={14}/></RouteLink>}<Button variant="outline" disabled={busy} onClick={()=>edit(post)}><PenLine size={14}/>编辑 / Edit</Button><Button variant="ghost" disabled={busy} onClick={()=>void remove(post)}>删除 / Delete</Button></div></div></article>)}</div>}{!loading&&!posts.length&&<div className="lab-empty"><Geometry kind={0}/><h2>你的第一篇，随时开始。</h2><p>No perfect beginnings required.</p><Button onClick={()=>edit({...blank})}>写下第一个想法 / Start writing</Button></div>}<div className="admin-pages"><Button variant="outline" disabled={!page||loading} onClick={()=>setPage(p=>p-1)}>上一页 / Previous</Button><span>{page+1} / {Math.max(1,Math.ceil(total/20))}</span><Button variant="outline" disabled={(page+1)*20>=total||loading} onClick={()=>setPage(p=>p+1)}>下一页 / Next</Button></div></>}
 <Admin open={moderate} onClose={()=>setModerate(false)} onChanged={()=>void refresh()} connected={connected} initialTab="comments"/>
 </>}{error&&<div className="lab-error" role="alert">{error}</div>}{notice&&<p className="lab-notice" role="status">{notice}</p>}
 </main></div>;
}
